# Generated by Django 3.2 on 2022-12-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='string', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_category',
            name='image',
            field=models.ImageField(default='sub_string', upload_to=''),
            preserve_default=False,
        ),
    ]
