# Generated by Django 3.2 on 2022-12-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221222_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='sub_category'),
        ),
    ]
