# Generated by Django 3.2 on 2022-12-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_sub_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='store.category'),
        ),
    ]
