# Generated by Django 3.2 on 2022-12-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='order_place',
        ),
        migrations.AddField(
            model_name='order',
            name='order_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
