# Generated by Django 3.1 on 2022-11-26 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='option',
            field=models.CharField(choices=[('O', 'Online'), ('D', 'On Delivery')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
